# Generated by Django 3.0.2 on 2020-02-05 07:35

import API.lib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obs', models.DateField()),
                ('description', models.TextField(null=True)),
                ('loc_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_apr', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=API.lib.RandomFileName('uploaded_images'))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ts_entered', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('entered_IP', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
