# Generated by Django 3.0.2 on 2020-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obs', models.DateField()),
                ('description', models.TextField(null=True)),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('loc_long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('ts_entered', models.TimeField(auto_now_add=True)),
                ('ts_updated', models.TimeField(auto_now=True)),
            ],
        ),
    ]
