# Generated by Django 3.0.2 on 2020-02-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200131_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidental',
            name='image_av',
        ),
        migrations.RemoveField(
            model_name='incidental',
            name='loc_name',
        ),
        migrations.AddField(
            model_name='incidental',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidental',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
