# Generated by Django 3.0.2 on 2020-02-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200202_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidental',
            old_name='loc_long',
            new_name='loc_lng',
        ),
    ]
