# Generated by Django 3.0.2 on 2020-02-02 11:12

import API.lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200202_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidental',
            name='image_ids',
            field=models.ImageField(blank=True, null=True, upload_to=API.lib.RandomFileName('uploaded_images')),
        ),
    ]
