# Generated by Django 3.0.2 on 2020-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200202_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidental',
            name='ts_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incidental',
            name='ts_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
